services:
  - type: web
    name: zara-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: PYTHONPATH=. gunicorn app.backend.app:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
    workingDir: . 