"""Add skills, experience, education, image to Profile

Revision ID: a679c43f2135
Revises: 52dd93dd8e07
Create Date: 2025-07-08 15:20:18.097466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a679c43f2135'
down_revision = '52dd93dd8e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('education', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('education')
        batch_op.drop_column('experience')
        batch_op.drop_column('skills')

    # ### end Alembic commands ###
